### PR TITLE
Introduce `wrap` option to disable wraping if set to false

### PR DESCRIPTION
**Pull request by andysprout**
Required to mimic select behaviour.

I'm currently trying to extend your react-autosuggest component to mimic a select box.

### CODE REVIEW

**Comment by moroshko** [comment]
Thanks for the PR!

From what I can see, you would like to achieve the following:
- When the last item is highlighted, and user hits `Down`, highlight the first item
- When the first item is highlighted, and user hits `Up`, highlight the last item

I explicitly avoided this behaviour when implementing [react-autosuggest](https://github.com/moroshko/react-autosuggest) because of the following [WAI-ARIA guideline for autocomplete components](https://www.w3.org/TR/wai-aria-practices/#autocomplete):

> Note that the arrows will wrap through the textbox when the top or bottom of the list is reached. For example, pressing the down arrow when the last choice is highlighted will move focus back to the textbox, pressing down again will move focus to the first item in the list. 

Also, I noticed that in a native `<select>`, when the last item is highlighted, and you hit `Down`, nothing happens (it doesn't wrap).

Do you have any accessibility guidelines that you follow while implementing the mentioned select box? Do you know any reputable sites that implement the behaviour you are trying to achieve?

**Comment by andysprout** [comment]
Thanks for your reply. Sorry I didn't write a more comprehensive description, you are correct about what I am trying to achieve.

I'm definitely not an expert on ARIA, so thanks for pointing me at the correct section. It's probably more correct to not wrap the highlighted suggestion. What do you think about changing the option from `allowNull` to `wrap` and just stopping when the user gets to the start or end of the data?

I really like react-autosuggest, the theming and aria compliance are much better than all the select libraries I have found. I hope to have something working today.

**Comment by moroshko** [comment]
@andysprout Sorry, I'll pass on this one. I feel like extending `react-autosuggest` to be a select box is beyond the scope of that project. I really appreciate your time and effort. Next time, it's probably a good idea to start a conversation in an issue first.

**Comment by andysprout** [comment]
No worries, at first I thought it was going to be a small change, but as I carried on the change required grew and grew. This was for a project my team needed anyway so we're continuing to use our fork build for now.

**Pull request closed without merging**
